# Generated by Django 2.2.12 on 2020-12-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=300)),
                ('documentoIdentidad', models.CharField(max_length=10, unique=True, verbose_name='documento de identidad')),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
