# Generated by Django 2.2.12 on 2020-12-02 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_turnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTurno',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paciente.turnos',),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='paciente.Paciente'),
        ),
    ]
