# Generated by Django 2.2.12 on 2020-12-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20201202_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=2000)),
                ('observaciones', models.CharField(max_length=2000)),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='paciente.Turnos')),
            ],
        ),
        migrations.DeleteModel(
            name='ChildTurno',
        ),
    ]
